export const listMenu=["home", "celulares", "computadores", "motocicletas"]

export type Product = {
    id: number;
    nombre: string;
    descripcion:string,
    marca: string;
    precio: string;
    tipo: string;
    reviews: number;
    fabricante: string;
    peso: string;
    dimensiones: string;
    pais: string;
    numeroModelo: number;
    color: string;
    material: string;
    piezas: number;
    caracteristicasEspeciales: string;
    componentesIncluidos: string;
    promocion?: number;
    images:string []
  };

  export type Categorias = {
    celulares: Product[];
    computadores: Product[];
    motocicletas: Product[];
  };

export const products:Categorias ={
    celulares:[
        {
          id:1,
          nombre:"Samsung A10",
          descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
          marca:"Samsung",
          precio:"3,500",
          tipo:"celular",
          reviews: 3.5,
          fabricante:"Samsung Electronics",
          peso: "150 gr",
          dimensiones:"16 x 8 x 0.7 cm",
          pais:"Corea del sur",
          numeroModelo:264722,
          color:"gris",
          material:"Silicona plástica",
          piezas:4,
          caracteristicasEspeciales:"Resistencia al agua",
          componentesIncluidos:"Manual de usuario, cargador, audífonos",
          promocion:40,
          images:["/public/samsungA10.jpg", "/public/samsungA10-2.png","/public/samsungA10.jpg", "/public/samsungA10-2.png"]
        },
        {
            id:2,
          nombre:"Samsung A21",
          descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
          marca:"Samsung",
          precio:"3,800",
          tipo:"celular",
          reviews: 4,
          fabricante:"Samsung Electronics",
          peso: "155 gr",
          dimensiones:"16.5 x 8.5 x 0.7 cm",
          pais:"Corea del sur",
          numeroModelo:264862,
          color:"negro",
          material:"Silicona plástica",
          piezas:2,
          caracteristicasEspeciales:"Resistencia al agua",
          componentesIncluidos:"Manual de usuario, cargador, audífonos",
          promocion:0,
          images:["/public/samsungA21.png", "/public/samsunga21-2.png", "/public/samsungA21.png", "/public/samsunga21-2.png"]
        },
        {
          id:3,
          nombre:"Xiaomi Redmi Note 13",
          descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
          marca:"Xiaomi",
          precio:"4,200",
          tipo:"celular",
          reviews: 4.5,
          fabricante:"Xiaomi Corporation",
          peso: "170 gr",
          dimensiones:"16.5 x 8.5 x 0.8 cm",
          pais:"China",
          numeroModelo:937462,
          color:"negro",
          material:"Silicona plástica",
          piezas:3,
          caracteristicasEspeciales:"Resistencia al agua, Pantalla AMOLED",
          componentesIncluidos:"Manual de usuario, cargador, audífonos",
          promocion:30,
          images:["/public/redmiNote13.png", "/public/redmiNote13-2.png", "/public/redmiNote13.png", "/public/redmiNote13-2.png"]
        },
        {
          id:4,
          nombre:"Xiaomi Redmi Note 11 64GB 4GB RAM",
          descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
          marca:"Xiaomi",
          precio:"4,000",
          tipo:"celular",
          reviews: 4,
          fabricante:"Xiaomi Corporation",
          peso: "160 gr",
          dimensiones:"16.2 x 8.3 x 0.8 cm",
          pais:"China",
          numeroModelo:937267,
          color:"blanco",
          material:"Silicona plástica",
          piezas:3,
          caracteristicasEspeciales:"Resistencia al agua, Pantalla AMOLED",
          componentesIncluidos:"Manual de usuario, cargador, audífonos",
          promocion:40,
          images:["/public/redmiNote11.png", "/public/redmiNote11-2.png", "/public/redmiNote11.png", "/public/redmiNote11-2.png"]
        },
        {
          id:5,
          nombre:"Iphone 14 Pro Max",
          descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
          marca:"Iphone",
          precio:"5,500",
          tipo:"celular",
          reviews: 4.5,
          fabricante:"Apple Inc.",
          peso: "180 gr",
          dimensiones:"14.2 x 7.8 x 0.7 cm",
          pais:"Estados Unidos",
          numeroModelo:5253526,
          color:"gris",
          material:"Aluminio",
          piezas:2,
          caracteristicasEspeciales:"Resistencia al agua",
          componentesIncluidos:"Manual de usuario, audífonos",
          promocion:0,
          images:["/public/iphone14.png", "/public/iphone14-2.png", "/public/iphone14.png", "/public/iphone14-2.png",]
        },
        {
          id:6,
          nombre:"Iphone 15 Pro Max",
          descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
          marca:"Iphone",
          precio:"6,500",
          tipo:"celular",
          reviews: 4.5,
          fabricante:"Apple Inc.",
          peso: "180 gr",
          dimensiones:"14.2 x 7.8 x 0.7 cm",
          pais:"Estados Unidos",
          numeroModelo:5254532,
          color:"gris",
          material:"Aluminio",
          piezas:2,
          caracteristicasEspeciales:"Resistencia al agua",
          componentesIncluidos:"Manual de usuario, audífonos",
          promocion:0,
          images:["/public/iphone15.png", "/public/iphone15-2.jpg", "/public/iphone15.png", "/public/iphone15-2.jpg"]
        },
        ],
    computadores:[
        {
            id: 7,
            nombre: "Lenovo ThinkBook 16 7ma Gen",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca: "Lenovo",
            precio: "8,500",
            tipo:"computador",
            reviews: 4.5,
            fabricante: "Lenovo Group, Ltd.",
            peso: "2.2 Kg",
            dimensiones: "35.8 x 24.6 x 1.8 cm",
            pais: "China",
            numeroModelo: 39384382,
            color: "gris",
            material: "Aluminio",
            piezas: 1,
            caracteristicasEspeciales: "Pantalla 4K, Teclado retroiluminado",
            componentesIncluidos: "Cargador, Manual de usuario",
            promocion:40,
            images:["/public/lenovo.png", "/public/lenovo-2.png", "/public/lenovo.png", "/public/lenovo-2.png"]
          },
          {
            id: 8,
            nombre: "Lenovo IdeaPad Pro 5i 16 9na Gen",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca: "Lenovo",
            precio: "10,500",
            tipo:"computador",
            reviews: 4.5,
            fabricante: "Lenovo Group, Ltd.",
            peso: "2.3 Kg",
            dimensiones: "35.8 x 24.6 x 1.8 cm",
            pais: "China",
            numeroModelo: 3940273,
            color: "gris",
            material: "Aluminio",
            piezas: 1,
            caracteristicasEspeciales: "Pantalla 4K, Teclado retroiluminado",
            componentesIncluidos: "Cargador, Manual de usuario",
            promocion:40,
            images:["/public/lenovo-2.png", "/public/lenovo.png", "/public/lenovo-2.png", "/public/lenovo.png"]
          },
          {
            id: 9,
            nombre: "MacBook Air de 13",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca: "MacBook",
            precio: "13,000",
            tipo:"computador",
            reviews: 4.5,
            fabricante: "Apple Inc.",
            peso: "2.5 Kg",
            dimensiones: "36.4 x 25.2 x 2.1 cm",
            pais: "Estados Unidos",
            numeroModelo: 49102933,
            color: "gris",
            material: "Policarbonato",
            piezas: 1,
            caracteristicasEspeciales: "Tarjeta gráfica dedicada, Sistema de enfriamiento avanzado",
            componentesIncluidos: "Cargador, Manual de usuario",
            promocion:0,
            images:["/public/macbook13.png", "/public/macbook13-2.png", "/public/macbook13.png", "/public/macbook13-2.png"]
          },
          {
            id: 10,
            nombre: "MacBook Air de 15",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca: "MacBook",
            precio: "15,000",
            tipo:"computador",
            reviews: 5,
            fabricante: "Apple Inc.",
            peso: "2.5 Kg",
            dimensiones: "36.4 x 25.2 x 2.1 cm",
            pais: "Estados Unidos",
            numeroModelo: 49117263,
            color: "gris",
            material: "Policarbonato",
            piezas: 1,
            caracteristicasEspeciales: "Tarjeta gráfica dedicada, Sistema de enfriamiento avanzado",
            componentesIncluidos: "Cargador, Manual de usuario",
            promocion:0,
            images:["/public/macbook13-2.png", "/public/macbook13.png", "/public/macbook13-2.png", "/public/macbook13.png"]
          },
          {
            id: 11,
            nombre: "Asus Vivobook Go 15",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca: "Asus",
            precio: "8,300",
            tipo:"computador",
            reviews: 4,
            fabricante: "Apple Inc.",
            peso: "2.5 Kg",
            dimensiones: "36 x 24.2 x 2 cm",
            pais: "Taiwán",
            numeroModelo: 37382923,
            color: "gris",
            material: "Aluminio",
            piezas: 1,
            caracteristicasEspeciales: "Tarjeta gráfica dedicada, Sistema de enfriamiento avanzado",
            componentesIncluidos: "Cargador, Manual de usuario",
            promocion:30,
            images:["/public/asusvivo.png", "/public/asusvivo-2.png", "/public/asusvivo.png", "/public/asusvivo-2.png"]
          },
          {
            id: 12,
            nombre: "Asus TUF Gaming A15",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca: "Asus",
            precio: "9,500",
            tipo:"computador",
            reviews: 4.5,
            fabricante: "Apple Inc.",
            peso: "2.6 Kg",
            dimensiones: "36.4 x 25.2 x 2.1 cm",
            pais: "Estados Unidos",
            numeroModelo: 49117263,
            color: "gris",
            material: "Aluminio",
            piezas: 1,
            caracteristicasEspeciales: "Tarjeta gráfica dedicada, Sistema de enfriamiento avanzado",
            componentesIncluidos: "Cargador, Manual de usuario",
            promocion:0,
            images:["/public/asusTUF.png", "/public/asusTUF-2.png", "/public/asusTUF.png", "/public/asusTUF-2.png"]
          },
          
    ],
    motocicletas:[
        {
            id:13,
            nombre:"DR 150 FI ABS",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca:"Suzuki",
            precio:"7,500",
            tipo:"motocicleta",
            reviews: 4,
            fabricante:"Suzuki Motors.",
            peso: "139 Kg",
            dimensiones:"154 x 84 x 54 cm",
            pais:"Colombia",
            numeroModelo:3746326,
            color:"negro",
            material:"Poliéter de fenileno",
            piezas:1,
            caracteristicasEspeciales:"Cilindraje de 149 cm cúbicos",
            componentesIncluidos:"calcomanías, manual de usuario",
            promocion:0,
            images:["/public/DR.png", "/public/DR-2.png", "/public/DR.png", "/public/DR-2.png"]
        },
        {
            id:14,
            nombre:"GIXXER 150 ABS",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca:"Suzuki",
            precio:"7,100",
            tipo:"motocicleta",
            reviews: 4,
            fabricante:"Suzuki Motors.",
            peso: "143 Kg",
            dimensiones:"154 x 84 x 54 cm",
            pais:"Colombia",
            numeroModelo:3746436,
            color:"negro",
            material:"Poliéter de fenileno",
            piezas:1,
            caracteristicasEspeciales:"Cilindraje de 149 cm cúbicos",
            componentesIncluidos:"calcomanías, manual de usuario",
            promocion:0,
            images:["/public/gixxer.png", "/public/gixxer-2.png", "/public/gixxer.png", "/public/gixxer-2.png"]
        },
        {
            id: 15,
            nombre: "GIXXER 250 ABS",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca: "Suzuki",
            precio: "8,500",
            tipo:"motocicleta",
            reviews: 5,
            fabricante: "Suzuki Motors.",
            peso: "156 Kg",
            dimensiones: "160 x 85 x 56 cm",
            pais: "Colombia",
            numeroModelo: 3746440,
            color: "azul",
            material: "Poliéter de fenileno",
            piezas: 1,
            caracteristicasEspeciales: "Cilindraje de 249 cm cúbicos",
            componentesIncluidos: "calcomanías, manual de usuario, herramientas básicas",
            promocion:20,
            images:["/public/gixxer250.png", "/public/Gixxer250-2.png", "/public/gixxer250.png", "/public/Gixxer250-2.png"]
        },
        {
            id: 16,
            nombre: "YZF-R3",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca: "Yamaha",
            precio: "5,500",
            tipo:"motocicleta",
            reviews: 5,
            fabricante: "Yamaha Motor Co., Ltd.",
            peso: "169 Kg",
            dimensiones: "209 x 72 x 114 cm",
            pais: "Japón",
            numeroModelo: 6572341,
            color: "azul",
            material: "Aluminio",
            piezas: 1,
            caracteristicasEspeciales: "Motor bicilíndrico de 321 cc",
            componentesIncluidos: "manual de usuario, herramientas básicas",
            promocion:30,
            images:["/public/yzf.png", "/public/yzf.png", "/public/yzf.png", "/public/yzf.png"]
          },
          {
            id: 17,
            nombre: "MT-07",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca: "Yamaha",
            precio: "7,500",
            tipo:"motocicleta",
            reviews: 4,
            fabricante: "Yamaha Motor Co., Ltd.",
            peso: "184 Kg",
            dimensiones: "208 x 74 x 110 cm",
            pais: "Japón",
            numeroModelo: 6587452,
            color: "negro",
            material: "Acero",
            piezas: 1,
            caracteristicasEspeciales: "Motor bicilíndrico de 689 cc",
            componentesIncluidos: "manual de usuario, herramientas básicas, protector de tanque",
            promocion:0,
            images:["/public/MT07.png", "/public/mt07-2.png", "/public/MT07.png", "/public/mt07-2.png"]
          },
          {
            id: 18,
            nombre: "XSR900",
            descripcion:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum expedita quasi at maxime quas saepe ea, deserunt molestias porro possimus neque eius nostrum, corporis numquam aliquid? Cumque praesentium veritatis officia.",
            marca: "Yamaha",
            precio: "9,500",
            tipo:"motocicleta",
            reviews: 5,
            fabricante: "Yamaha Motor Co., Ltd.",
            peso: "195 Kg",
            dimensiones: "215 x 81 x 115 cm",
            pais: "Japón",
            numeroModelo: 6591234,
            color: "rojo",
            material: "Acero y aluminio",
            piezas: 1,
            caracteristicasEspeciales: "Motor tricilíndrico de 847 cc",
            componentesIncluidos: "manual de usuario, herramientas básicas, cubierta de asiento",
            promocion:0,
            images:["/public/xsr900.png", "/public/xsr900-2.png", "/public/xsr900.png", "/public/xsr900-2.png"]
          }
    ]
    }